import React from "react";

const page = () => {
  return (
    <main className="container mx-auto max-w-[1200px]">
      <h1 className="mt-[100px]">API</h1>
      <p className="mt-5">
        An API key is a specialized authentication tool designed to secure the
        NeutronX API service and block unauthorized access to your data. Each
        user receives a unique string generated by the system to verify their
        authenticity when using the API. Users must include their API key in the
        request header to authenticate themselves. This measure helps prevent
        malicious attacks and misuse, safeguarding the integrity and
        functionality of our system.
      </p>
      <h4 className="text-3xl mt-20">Steps to get a key </h4>
      <div className="flex text-black items-center">
        <span className="relative z-100 size-6 bg-accent rounded-full  flex items-center justify-center dark:text-white shrink-0 roboto font-semibold">
          1
        </span>
        <div className="h-[50px] border border-purple rounded-[18px] w-[240px] text-white flex items-center justify-center font-medium bg-[#221D2F] -top-[100px] shrink-0">
          Sign up
        </div>
      </div>
    </main>
  );
};

export default page;
